In [136]:
import pandas as pd
import numpy as np
import lasio

las = lasio.read(r'../../data_well_log/las_files_Lithostrat_data/7_1-1.las')
df = las.df()
df.tail()

,FORCE_2020_LITHOFACIES_CONFIDENCE,FORCE_2020_LITHOFACIES_LITHOLOGY,CALI,BS,DCAL,MUDWEIGHT,ROP,RDEP,RSHA,RMED,SP,DTC,NPHI,GR,RHOB,DRHO,DEPTH_MD,X_LOC,Y_LOC,Z_LOC
DEPT,,,,,,,,,,,,,,,,,,,,
2815.1048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.430444,1.138537,1.139098,19.852074,NaN,NaN,NaN,NaN,NaN,2815.104736,450379.40625,6406641.0,-2780.967529
2815.2568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.510404,1.138337,1.139497,20.274757,NaN,NaN,NaN,NaN,NaN,2815.256836,450379.40625,6406641.0,-2781.119629
2815.4088,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.591403,1.138057,1.138816,20.716501,NaN,NaN,NaN,NaN,NaN,2815.408691,450379.40625,6406641.0,-2781.271484
2815.5608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.136922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2815.7128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.134880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
df["FORCE_2020_LITHOFACIES_LITHOLOGY"].unique()

array([   nan, 30000., 65000., 65030., 70000., 99000., 80000., 70032.])

In [138]:
df_filled = df.fillna(0)

In [139]:
df_filled.head()

,FORCE_2020_LITHOFACIES_CONFIDENCE,FORCE_2020_LITHOFACIES_LITHOLOGY,CALI,BS,DCAL,MUDWEIGHT,ROP,RDEP,RSHA,RMED,SP,DTC,NPHI,GR,RHOB,DRHO,DEPTH_MD,X_LOC,Y_LOC,Z_LOC
DEPT,,,,,,,,,,,,,,,,,,,,
82.6008,0.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
82.7528,0.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
82.9048,0.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83.0568,0.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83.2088,0.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [140]:
df_filled = df_filled.drop(['FORCE_2020_LITHOFACIES_CONFIDENCE', 'X_LOC', 'Y_LOC', 'Z_LOC'], axis=1)

In [141]:
df_filled.columns

Index(['FORCE_2020_LITHOFACIES_LITHOLOGY', 'CALI', 'BS', 'DCAL', 'MUDWEIGHT',
       'ROP', 'RDEP', 'RSHA', 'RMED', 'SP', 'DTC', 'NPHI', 'GR', 'RHOB',
       'DRHO', 'DEPTH_MD'],
      dtype='object')

In [142]:
columns = ['CALI', 'BS', 'DCAL', 'ROP', 'RDEP', 'RSHA', 'RMED', 'SP', 'DTC', 'NPHI', 'GR', 'RHOB', 'DRHO']

# Apply normalization to selected columns
df_normalized = df_filled[columns].apply(lambda x: (x - x.min()) / (x.max() - x.min()))

# Concatenate the normalized columns with the remaining columns
# df_normalized = pd.concat([df_normalized, df_filled.drop(columns, axis=1)], axis=1)

df_normalized.head()

,CALI,BS,DCAL,ROP,RDEP,RSHA,RMED,SP,DTC,NPHI,GR,RHOB,DRHO
DEPT,,,,,,,,,,,,,
82.6008,0.0,1.0,0.551147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.269537
82.7528,0.0,1.0,0.551147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.269537
82.9048,0.0,1.0,0.551147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.269537
83.0568,0.0,1.0,0.551147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.269537
83.2088,0.0,1.0,0.551147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.269537

In [143]:
X = df_normalized
y = df_filled['FORCE_2020_LITHOFACIES_LITHOLOGY']

In [144]:
y.head()

DEPT
82.6008    0.0
82.7528    0.0
82.9048    0.0
83.0568    0.0
83.2088    0.0
Name: FORCE_2020_LITHOFACIES_LITHOLOGY, dtype: float64

In [145]:
lithology_keys = {30000: 'Sandstone',
                 65030: 'Sandstone/Shale',
                 65000: 'Shale',
                 80000: 'Marl',
                 74000: 'Dolomite',
                 70000: 'Limestone',
                 70032: 'Chalk',
                 88000: 'Halite',
                 86000: 'Anhydrite',
                 99000: 'Tuff',
                 90000: 'Coal',
                 93000: 'Basement',
                 0: 'None'}

In [146]:
y = y.map(lithology_numbers)

In [147]:
y

DEPT
82.6008      12
82.7528      12
82.9048      12
83.0568      12
83.2088      12
             ..
2815.1048    12
2815.2568    12
2815.4088    12
2815.5608    12
2815.7128    12
Name: FORCE_2020_LITHOFACIES_LITHOLOGY, Length: 17982, dtype: int64

In [153]:
X = X.transpose()
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, CALI to DRHO
Columns: 17982 entries, 82.600799561 to 2815.7127996
dtypes: float64(17982)
memory usage: 1.8+ MB

D: The number of depth points. This corresponds to the length of the DataFrame (df).

N: The number of logging curves (features). This corresponds to the length of the logging_curves list.

data: The values of the selected logging curves (logging_curves) from the DataFrame (X) converted into a NumPy array.

input_tensor: Reshaped tensor with dimensions (D, 1, N), where:

    The first dimension (D) represents the depth points.
    The second dimension (1) represents the channel. In this case, since we are dealing with 1D input data, it is set to 1.
    
The third dimension (N) represents the logging curves (features).


values along the x-axis correspond to the different logging curves, and the values along the y-axis correspond to the depth points.

In [162]:
# Reshape the DataFrame. The input data: 1D 

# data = X.to_numpy()

D = len(X.index) # Why is it the number of column when it has to be depth!!!!
N = len(X.columns)

# Check D var again
print(D)
print(len(X))
# depth_values = X.index.tolist()
# print(depth_values)
# input_tensor = np.reshape(data, (D, 1, N))

13
13